function [performance_metrics, design_params] = diffraction_limited_multiband_analysis(varargin)
% DIFFRACTION_LIMITED_MULTIBAND_ANALYSIS - Y/J/H spectrograph performance
%
% Builds a diffraction-driven reference design in band Y and evaluates the
% corresponding Y/J/H grating densities, detector coverage, resolving power,
% diffraction-limited spot sampling, fibre-image overlap, and pseudo-slit
% capacity.
%
% Resolving power is evaluated using both limits:
%
%   R_geom(lambda) = rho * lambda * F1 * W / s1
%   R_diff         = rho * W / 1.22
%
% The effective resolving power is:
%
%   R_eff(lambda) = min(R_geom(lambda), R_diff)
%
% The transition wavelength is identified where R_geom reaches R_diff.
%
% Inputs (parameter/value pairs):
%   'R_Y'              - Reference diffraction-limited resolving power in Y
%   's1'               - Fibre/slit width [m]
%   'nPix'             - Detector pixels along dispersion direction
%   'pix'              - Detector pixel pitch [m]
%   'F1'               - Collimator f-number
%   'samp'             - Required Airy-diameter sampling [pixels]
%   'fibre_separation' - Fibre core separation [m]
%   'slit_length'      - Available pseudo-slit length [m]
%   'rho_Y'            - Band-Y grating density [lines/m]
%   Y/J/H wavelength limits are also configurable.
%
% Outputs:
%   performance_metrics - Resolving power, coverage, spot, overlap and fibre data
%   design_params       - Focal lengths, diameters, grating densities and angles
%
% Example:
%   [metrics, design] = diffraction_limited_multiband_analysis();

%% Input parsing
p = inputParser;

addParameter(p, 'R_Y', 7880, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 's1', 4.9e-6, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'nPix', 2000, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'pix', 18e-6, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'F1', 4.55, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'samp', 2.5, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'fibre_separation', 25e-6, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'slit_length', 2.2e-3, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);

addParameter(p, 'L_min_Y', 0.960e-6, @isnumeric);
addParameter(p, 'L_max_Y', 1.115e-6, @isnumeric);
addParameter(p, 'L_min_J', 1.150e-6, @isnumeric);
addParameter(p, 'L_max_J', 1.345e-6, @isnumeric);
addParameter(p, 'L_min_H', 1.490e-6, @isnumeric);
addParameter(p, 'L_max_H', 1.780e-6, @isnumeric);

addParameter(p, 'rho_Y', 650e3, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);

parse(p, varargin{:});
params = p.Results;

%% Derived quantities
params.L_c_Y = mean([params.L_min_Y, params.L_max_Y]);
params.L_c_J = mean([params.L_min_J, params.L_max_J]);
params.L_c_H = mean([params.L_min_H, params.L_max_H]);
params.length_det = params.nPix * params.pix;

fprintf('=== Diffraction-Limited Multi-Band Analysis ===\n');
fprintf('Detector: %d pixels, %.1f mm length\n', ...
    params.nPix, params.length_det * 1e3);
fprintf('Reference grating density (Y): %.0f lines/mm\n', ...
    params.rho_Y * 1e-3);

%% Band Y reference design
arg = params.rho_Y * params.L_c_Y / 2;

if abs(arg) > 1
    error('Band-Y reference configuration does not permit Littrow operation.');
end

alpha = asin(arg);

% Illuminated grating width from the diffraction-limited resolving power:
% R_diff = rho * W / 1.22
W = params.R_Y * 1.22 / params.rho_Y;

D1 = W * cos(alpha);
f1 = params.F1 * D1;

% Camera sampling is set from the Airy diameter at the shortest Y wavelength.
s2_diff = params.samp * params.pix;
F2 = s2_diff / (2.44 * params.L_min_Y);

beta_min_Y = asin(params.rho_Y * params.L_min_Y - sin(alpha));
beta_max_Y = asin(params.rho_Y * params.L_max_Y - sin(alpha));

D2 = W * cos(beta_min_Y);
f2 = F2 * D2;

% Geometrical slit image at the detector.
s2_geo = params.s1 * F2 / params.F1;
s2_geo_px = s2_geo / params.pix;

length_Y = f2 * (tan(beta_max_Y) - tan(beta_min_Y));
length_Y_px = length_Y / params.pix;

fprintf('\n--- Band Y Reference Design ---\n');
fprintf('Littrow angle: %.1f deg\n', rad2deg(alpha));
fprintf('Projected grating width W: %.2f mm\n', W * 1e3);
fprintf('Beam diameters: D1 = %.2f mm, D2 = %.2f mm\n', ...
    D1 * 1e3, D2 * 1e3);
fprintf('Focal lengths: f1 = %.2f mm, f2 = %.2f mm\n', ...
    f1 * 1e3, f2 * 1e3);
fprintf('Camera f-number: F2 = %.2f\n', F2);
fprintf('Geometrical slit image: %.2f px\n', s2_geo_px);

%% J and H cross-band scaling
% Keep the same Littrow angle at the central wavelength of each band.
rho_J = (2 * sin(alpha)) / params.L_c_J;
rho_H = (2 * sin(alpha)) / params.L_c_H;

R_diff_Y = params.rho_Y * W / 1.22;
R_diff_J = rho_J * W / 1.22;
R_diff_H = rho_H * W / 1.22;

beta_min_J = asin(rho_J * params.L_min_J - sin(alpha));
beta_max_J = asin(rho_J * params.L_max_J - sin(alpha));
beta_min_H = asin(rho_H * params.L_min_H - sin(alpha));
beta_max_H = asin(rho_H * params.L_max_H - sin(alpha));

length_J = f2 * (tan(beta_max_J) - tan(beta_min_J));
length_H = f2 * (tan(beta_max_H) - tan(beta_min_H));

length_J_px = length_J / params.pix;
length_H_px = length_H / params.pix;

fprintf('\n--- Cross-Band Scaling ---\n');
fprintf('Band Y: rho = %.0f lines/mm, R_diff = %.0f\n', ...
    params.rho_Y * 1e-3, R_diff_Y);
fprintf('Band J: rho = %.0f lines/mm, R_diff = %.0f\n', ...
    rho_J * 1e-3, R_diff_J);
fprintf('Band H: rho = %.0f lines/mm, R_diff = %.0f\n', ...
    rho_H * 1e-3, R_diff_H);

%% Detector coverage
rho_all = [params.rho_Y, rho_J, rho_H];
beta_min_all = [beta_min_Y, beta_min_J, beta_min_H];
beta_max_all = [beta_max_Y, beta_max_J, beta_max_H];

coverage = verify_detector_coverage(...
    params, f2, beta_min_all, beta_max_all, rho_all, alpha);

%% Resolving power and regime transitions
[fig_resolving, resolving_data] = analyze_resolving_power(...
    params, rho_all, W, coverage);

%% Fibre-image overlap
[overlap_metrics, fig_overlap] = ...
    analyze_fibre_overlap(params, F2, f2, f1);

%% Diffraction-limited spot-size evolution
[spot_sampling, fig_spotsize] = ...
    analyze_spot_size_evolution(params, F2);

%% Maximum pseudo-slit fibre count
max_fibres = calculate_maximum_fibres(params, f2, f1);

%% Outputs
performance_metrics = struct(...
    'resolving_power', resolving_data, ...
    'detector_coverage', coverage, ...
    'fibre_overlap', overlap_metrics, ...
    'max_fibres', max_fibres, ...
    'spot_sampling', spot_sampling, ...
    'geometric_slit_image_px', s2_geo_px, ...
    'figures', struct(...
        'resolving_power', fig_resolving, ...
        'fibre_overlap', fig_overlap, ...
        'spot_size', fig_spotsize));

design_params = struct(...
    'focal_lengths', struct('f1', f1, 'f2', f2), ...
    'diameters', struct('D1', D1, 'D2', D2), ...
    'projected_grating_width', W, ...
    'camera_f_number', F2, ...
    'grating_densities', struct(...
        'rho_Y', params.rho_Y, ...
        'rho_J', rho_J, ...
        'rho_H', rho_H), ...
    'diffraction_limits', struct(...
        'R_Y', R_diff_Y, ...
        'R_J', R_diff_J, ...
        'R_H', R_diff_H), ...
    'angles', struct(...
        'alpha', alpha, ...
        'beta_min', beta_min_all, ...
        'beta_max', beta_max_all), ...
    'spectral_length_px', ...
        [length_Y_px, length_J_px, length_H_px]);

fprintf('\n=== Analysis Complete ===\n');

end


function coverage = verify_detector_coverage(...
    params, f2, beta_min, beta_max, rho, alpha)

    bands = {'Y', 'J', 'H'};
    spectral_lengths = ...
        abs(f2 * (tan(beta_max) - tan(beta_min)));

    coverage = struct();

    fprintf('\n--- Detector Coverage ---\n');

    for i = 1:3

        fits = spectral_lengths(i) <= params.length_det;

        if fits
            cutoff_wavelength = NaN;

            fprintf('Band %s: fits detector (%.0f / %.0f px)\n', ...
                bands{i}, ...
                spectral_lengths(i) / params.pix, ...
                params.nPix);

        else
            x_min = f2 * tan(beta_min(i));
            x_cut = x_min + params.length_det;
            beta_cut = atan(x_cut / f2);

            cutoff_wavelength = ...
                (sin(beta_cut) + sin(alpha)) / rho(i);

            fprintf('Band %s: exceeds detector (%.0f / %.0f px)\n', ...
                bands{i}, ...
                spectral_lengths(i) / params.pix, ...
                params.nPix);

            fprintf('  Cutoff wavelength: %.1f nm\n', ...
                cutoff_wavelength * 1e9);
        end

        coverage.(['band_', bands{i}]) = struct(...
            'fits', fits, ...
            'spectral_length', spectral_lengths(i), ...
            'cutoff_wavelength', cutoff_wavelength);
    end
end


function [fig, resolving_data] = analyze_resolving_power(...
    params, rho, W, coverage)

    bands = {'Y', 'J', 'H'};

    lambda_limits = [...
        params.L_min_Y, params.L_max_Y; ...
        params.L_min_J, params.L_max_J; ...
        params.L_min_H, params.L_max_H];

    lambda = cell(1, 3);
    R_geom = cell(1, 3);
    R_eff = cell(1, 3);

    R_diff = rho .* W / 1.22;
    transition_lambda = NaN(1, 3);
    regime = strings(1, 3);

    fig = figure(...
        'Name', 'Resolving Power Analysis', ...
        'Position', [100, 100, 950, 650]);

    hold on;
    colors = lines(3);

    fprintf('\n--- Resolving Power Regimes ---\n');

    for i = 1:3

        lambda{i} = linspace(...
            lambda_limits(i, 1), ...
            lambda_limits(i, 2), ...
            500);

        % Slit-limited resolving power.
        R_geom{i} = ...
            (rho(i) .* lambda{i} * params.F1 * W) ./ params.s1;

        % Effective resolving power is set by the smaller physical limit.
        R_eff{i} = min(R_geom{i}, R_diff(i));

        % Find the first wavelength where diffraction becomes limiting.
        transition_idx = find(R_geom{i} >= R_diff(i), 1);

        if isempty(transition_idx)

            if all(R_geom{i} < R_diff(i))
                regime(i) = "slit-limited";
                fprintf('Band %s: slit-limited across the full band\n', ...
                    bands{i});
            else
                regime(i) = "diffraction-limited";
                fprintf('Band %s: diffraction-limited across the full band\n', ...
                    bands{i});
            end

        elseif transition_idx == 1

            transition_lambda(i) = lambda{i}(1);
            regime(i) = "diffraction-limited";

            fprintf(['Band %s: diffraction-limited across the full band ' ...
                     '(R_diff = %.0f)\n'], ...
                bands{i}, R_diff(i));

        else

            % Interpolate the crossing between neighbouring samples.
            x1 = lambda{i}(transition_idx - 1);
            x2 = lambda{i}(transition_idx);

            y1 = R_geom{i}(transition_idx - 1) - R_diff(i);
            y2 = R_geom{i}(transition_idx) - R_diff(i);

            transition_lambda(i) = ...
                x1 - y1 * (x2 - x1) / (y2 - y1);

            regime(i) = "transition";

            fprintf('Band %s: transition at %.1f nm, R = %.0f\n', ...
                bands{i}, ...
                transition_lambda(i) * 1e9, ...
                R_diff(i));

            fprintf('  shorter wavelengths: slit-limited\n');
            fprintf('  longer wavelengths: diffraction-limited\n');
        end

        % Main performance curve.
        plot(...
            lambda{i} * 1e9, ...
            R_eff{i}, ...
            'LineWidth', 2.5, ...
            'Color', colors(i, :), ...
            'DisplayName', ['Band ', bands{i}, ' effective']);

        % Slit-limited prediction.
        plot(...
            lambda{i} * 1e9, ...
            R_geom{i}, ...
            ':', ...
            'LineWidth', 1.2, ...
            'Color', colors(i, :), ...
            'HandleVisibility', 'off');

        % Diffraction ceiling.
        plot(...
            lambda{i}([1, end]) * 1e9, ...
            [R_diff(i), R_diff(i)], ...
            '--', ...
            'LineWidth', 1.2, ...
            'Color', colors(i, :), ...
            'HandleVisibility', 'off');

        % Transition marker.
        if ~isnan(transition_lambda(i))
            plot(...
                transition_lambda(i) * 1e9, ...
                R_diff(i), ...
                'o', ...
                'MarkerSize', 6, ...
                'MarkerFaceColor', colors(i, :), ...
                'MarkerEdgeColor', colors(i, :), ...
                'HandleVisibility', 'off');
        end

        % Detector cutoff marker.
        band_coverage = coverage.(['band_', bands{i}]);

        if ~band_coverage.fits
            xline(...
                band_coverage.cutoff_wavelength * 1e9, ...
                '-.', ...
                'Color', colors(i, :), ...
                'LineWidth', 1.0, ...
                'HandleVisibility', 'off');
        end
    end

    xlabel('Wavelength [nm]');
    ylabel('Resolving Power R');
    title('Effective Resolving Power vs Wavelength');

    legend('show', 'Location', 'best');
    grid on;
    box on;

    resolving_data = struct(...
        'lambda_Y', lambda{1}, ...
        'R_geom_Y', R_geom{1}, ...
        'R_diff_Y', R_diff(1), ...
        'R_eff_Y', R_eff{1}, ...
        'transition_Y', transition_lambda(1), ...
        'regime_Y', regime(1), ...
        ...
        'lambda_J', lambda{2}, ...
        'R_geom_J', R_geom{2}, ...
        'R_diff_J', R_diff(2), ...
        'R_eff_J', R_eff{2}, ...
        'transition_J', transition_lambda(2), ...
        'regime_J', regime(2), ...
        ...
        'lambda_H', lambda{3}, ...
        'R_geom_H', R_geom{3}, ...
        'R_diff_H', R_diff(3), ...
        'R_eff_H', R_eff{3}, ...
        'transition_H', transition_lambda(3), ...
        'regime_H', regime(3));
end


function [metrics, fig] = analyze_fibre_overlap(...
    params, F2, f2, f1)

    lambda = linspace(...
        params.L_min_Y, ...
        params.L_max_H, ...
        1000);

    airy_radius_px = ...
        F2 * 1.22 * lambda / params.pix;

    magnification = f2 / f1;

    fibre_separation_px = ...
        (params.fibre_separation / params.pix) * magnification;

    fig = figure(...
        'Name', 'Fibre Spot Overlap Analysis', ...
        'Position', [100, 100, 900, 600]);

    hold on;

    x = lambda * 1e9;

    upper_1 = airy_radius_px - fibre_separation_px / 2;
    lower_1 = -airy_radius_px - fibre_separation_px / 2;

    upper_2 = airy_radius_px + fibre_separation_px / 2;
    lower_2 = -airy_radius_px + fibre_separation_px / 2;

    fill(...
        [x, fliplr(x)], ...
        [lower_1, fliplr(upper_1)], ...
        'r', ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.1, ...
        'DisplayName', 'Fibre 1 Airy envelope');

    fill(...
        [x, fliplr(x)], ...
        [lower_2, fliplr(upper_2)], ...
        'b', ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.1, ...
        'DisplayName', 'Fibre 2 Airy envelope');

    yline(...
        fibre_separation_px / 2, ...
        'k--', ...
        'LineWidth', 1, ...
        'DisplayName', 'Fibre centres');

    yline(...
        -fibre_separation_px / 2, ...
        'k--', ...
        'LineWidth', 1, ...
        'HandleVisibility', 'off');

    plot(x, upper_2, 'b-', ...
        'LineWidth', 1.5, 'HandleVisibility', 'off');
    plot(x, lower_2, 'b-', ...
        'LineWidth', 1.5, 'HandleVisibility', 'off');
    plot(x, upper_1, 'r-', ...
        'LineWidth', 1.5, 'HandleVisibility', 'off');
    plot(x, lower_1, 'r-', ...
        'LineWidth', 1.5, 'HandleVisibility', 'off');

    xlabel('Wavelength [nm]');
    ylabel('Position [pixels]');
    title('Fibre Spot Overlap Analysis');

    legend('show', 'Location', 'best');
    grid on;
    box on;

    gap = lower_2 - upper_1;
    idx = find(gap <= 0, 1);

    if isempty(idx)

        overlap_occurs = false;
        overlap_wavelength = NaN;

        fprintf('\nFibre Airy envelopes do not overlap within the wavelength range.\n');

    else

        overlap_occurs = true;

        if idx == 1
            overlap_wavelength = lambda(1);
        else
            x1 = lambda(idx - 1);
            x2 = lambda(idx);

            g1 = gap(idx - 1);
            g2 = gap(idx);

            overlap_wavelength = ...
                x1 - g1 * (x2 - x1) / (g2 - g1);
        end

        fprintf('\nFibre Airy envelopes overlap from approximately %.2f um.\n', ...
            overlap_wavelength * 1e6);
    end

    metrics = struct(...
        'overlap_occurs', overlap_occurs, ...
        'overlap_wavelength', overlap_wavelength, ...
        'fibre_separation_px', fibre_separation_px, ...
        'max_airy_radius_px', max(airy_radius_px));
end


function [spot_sampling, fig] = ...
    analyze_spot_size_evolution(params, F2)

    bands = {'Y', 'J', 'H'};

    lambda = {...
        linspace(params.L_min_Y, params.L_max_Y, 300), ...
        linspace(params.L_min_J, params.L_max_J, 300), ...
        linspace(params.L_min_H, params.L_max_H, 300)};

    fig = figure(...
        'Name', 'Spot Size Evolution', ...
        'Position', [100, 100, 900, 600]);

    hold on;

    colors = lines(3);
    spot = cell(1, 3);

    for i = 1:3

        spot{i} = ...
            F2 * 2.44 * lambda{i} / params.pix;

        plot(...
            lambda{i} * 1e9, ...
            spot{i}, ...
            'LineWidth', 2, ...
            'Color', colors(i, :), ...
            'DisplayName', ['Band ', bands{i}]);
    end

    yline(...
        params.samp, ...
        'r--', ...
        'LineWidth', 2, ...
        'DisplayName', ...
        sprintf('Target Sampling (%.1f px)', params.samp));

    xlabel('Wavelength [nm]');
    ylabel('Airy Diameter [pixels]');
    title('Diffraction-Limited Spot Size vs Wavelength');

    legend('show', 'Location', 'southeast');
    grid on;
    box on;

    spot_sampling = struct(...
        'Y_min', min(spot{1}), ...
        'Y_max', max(spot{1}), ...
        'J_min', min(spot{2}), ...
        'J_max', max(spot{2}), ...
        'H_min', min(spot{3}), ...
        'H_max', max(spot{3}));
end


function max_fibres = calculate_maximum_fibres(...
    params, f2, f1)

    magnification = f2 / f1;

    fibre_pitch_px = ...
        (params.fibre_separation / params.pix) * magnification;

    n = 1:20;
    N = 1 + 6 * ((n .* (n - 1)) / 2);

    slit_limit_px = params.slit_length / params.pix;
    required_length_px = (N - 1) .* fibre_pitch_px;

    valid_indices = ...
        find(required_length_px <= slit_limit_px);

    if isempty(valid_indices)

        max_fibres = 0;

        warning(...
            'No valid fibre configuration found within slit length constraint.');

    else

        max_fibres = N(valid_indices(end));

        fprintf('\nMaximum number of fibres: %.0f\n', ...
            max_fibres);
    end
end
